# config/cable.yml

# NOTE: 開発でも DB バックで動かす設定に変更
development:
  adapter: solid_cable
  # 単一DB(A構成)なら connects_to は不要（primary を使います）
  # 別DBに分離したい場合は下記を有効化し、database.yml に development:cable を用意してください。
  # connects_to:
  #   database:
  #     writing: cable
  polling_interval: 0.1.seconds
  message_retention: 1.day

test:
  adapter: test

production:
  adapter: solid_cable
  connects_to:
    database:
      writing: cable
  polling_interval: 0.1.seconds
  message_retention: 1.day
